---
addons:
  chrome: stable
  firefox: latest
before_script:
  - "wget -N https://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_linux64.zip"
  - "unzip ~/chromedriver_linux64.zip -d ~/"
  - "rm ~/chromedriver_linux64.zip"
  - "sudo mv -f ~/chromedriver /usr/local/share/"
  - "sudo chmod +x /usr/local/share/chromedriver"
  - "sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver"
env: "-DJANGO=3.0.3 DB=sqlite3"
install:
  - "pip install -r requirements.txt"
language: python
python:
  - "3.8"
script:
  - "python manage.py test functional_tests"
sudo: required
