# Generated by Django 3.0.3 on 2020-04-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0005_auto_20200423_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepic',
            name='is_profile_pic',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
