# Generated by Django 3.0.3 on 2020-04-23 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0006_profilepic_is_profile_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfilePic',
            new_name='PictureContainer',
        ),
    ]
